Error: Number error cause
    at *
    at *
    at *
    at *
    at *
    at *
    at * {
  [cause]: *
}
Error: Object cause
    at *
    at *
    at *
    at *
    at *
    at *
    at * {
  [cause]: {
    message: 'Unique',
    name: 'Error',
    stack: 'Error: Unique\n' +
      '    at Module._compile (node:internal*modules*cjs*loader:*:*)'
  }
}
Error: undefined cause
    at *
    at *
    at *
    at *
    at *
    at *
    at * {
  [cause]: undefined
}
Error: cause that throws
    at *
    at *
    at *
    at *
    at *
    at *
    at * {
  [cause]: [Getter]
}
RangeError: New Stack Frames
    at *
*[*m    at  *[*m {
  [cause]: FoobarError: Individual message
      at Object.<anonymous> *[*m(**[*mtest*fixtures*util*util-inspect-error-cause.js:*:**[*m)*[*m
  *[*m    at Module._compile (node:internal*modules*cjs*loader:*:*)*[*m
  *[*m    ... * lines matching cause stack trace ...*[*m
  *[*m    at *[*m {
    status: *[*m'Feeling good'*[*m,
    extraProperties: *[*m'Yes!'*[*m,
    [cause]: TypeError: Inner error
        at Object.<anonymous> *[*m(**[*mtest*fixtures*util*util-inspect-error-cause.js:*:**[*m)*[*m
    *[*m    at Module._compile (node:internal*modules*cjs*loader:*:*)*[*m
    *[*m    at Module._extensions..js (node:internal*modules*cjs*loader:*:*)*[*m
    *[*m    at Module.load (node:internal*modules*cjs*loader:*:*)*[*m
    *[*m    at Module._load (node:internal*modules*cjs*loader:*:*)*[*m
    *[*m    at Function.executeUserEntryPoint [as runMain] (node:internal*modules*run_main:*:*)*[*m
    *[*m    at *[*m
  }
}
Error: Stack causes
    at Object.<anonymous> *[*m(**[*mtest*fixtures*util*util-inspect-error-cause.js:*:**[*m)*[*m
*[*m    at Module._compile (node:internal*modules*cjs*loader:*:*)*[*m
*[*m    ... * lines matching cause stack trace ...*[*m
*[*m    at *[*m {
  [cause]: FoobarError: Individual message
      at Object.<anonymous> *[*m(**[*mtest*fixtures*util*util-inspect-error-cause.js:*:**[*m)*[*m
  *[*m    at Module._compile (node:internal*modules*cjs*loader:*:*)*[*m
  *[*m    ... * lines matching cause stack trace ...*[*m
  *[*m    at *[*m {
    status: *[*m'Feeling good'*[*m,
    extraProperties: *[*m'Yes!'*[*m,
    [cause]: TypeError: Inner error
        at Object.<anonymous> *[*m(**[*mtest*fixtures*util*util-inspect-error-cause.js:*:**[*m)*[*m
    *[*m    at Module._compile (node:internal*modules*cjs*loader:*:*)*[*m
    *[*m    at Module._extensions..js (node:internal*modules*cjs*loader:*:*)*[*m
    *[*m    at Module.load (node:internal*modules*cjs*loader:*:*)*[*m
    *[*m    at Module._load (node:internal*modules*cjs*loader:*:*)*[*m
    *[*m    at Function.executeUserEntryPoint [as runMain] (node:internal*modules*run_main:*:*)*[*m
    *[*m    at *[*m
  }
}
RangeError: New Stack Frames
    at *
*[*m    at  *[*m {
  [cause]: Error: Stack causes
      at Object.<anonymous> *[*m(**[*mtest*fixtures*util*util-inspect-error-cause.js:*:**[*m)*[*m
  *[*m    at Module._compile (node:internal*modules*cjs*loader:*:*)*[*m
  *[*m    ... * lines matching cause stack trace ...*[*m
  *[*m    at *[*m {
    [cause]: FoobarError: Individual message
        at Object.<anonymous> *[*m(**[*mtest*fixtures*util*util-inspect-error-cause.js:*:**[*m)*[*m
    *[*m    at Module._compile (node:internal*modules*cjs*loader:*:*)*[*m
    *[*m    ... * lines matching cause stack trace ...*[*m
    *[*m    at *[*m {
      status: *[*m'Feeling good'*[*m,
      extraProperties: *[*m'Yes!'*[*m,
      [cause]: TypeError: Inner error
          at Object.<anonymous> *[*m(**[*mtest*fixtures*util*util-inspect-error-cause.js:*:**[*m)*[*m
      *[*m    at Module._compile (node:internal*modules*cjs*loader:*:*)*[*m
      *[*m    at Module._extensions..js (node:internal*modules*cjs*loader:*:*)*[*m
      *[*m    at Module.load (node:internal*modules*cjs*loader:*:*)*[*m
      *[*m    at Module._load (node:internal*modules*cjs*loader:*:*)*[*m
      *[*m    at Function.executeUserEntryPoint [as runMain] (node:internal*modules*run_main:*:*)*[*m
      *[*m    at *[*m
    }
  }
}
RangeError: New Stack Frames
    at *
    at * {
  [cause]: FoobarError: Individual message
      at *
      at *
      ... * lines matching cause stack trace ...
      at * {
    status: 'Feeling good',
    extraProperties: 'Yes!',
    [cause]: TypeError: Inner error
        at *
        at *
        at *
        at *
        at *
        at *
        at *
  }
}
Error: Stack causes
    at *
    at *
    ... * lines matching cause stack trace ...
    at * {
  [cause]: FoobarError: Individual message
      at *
      at *
      ... * lines matching cause stack trace ...
      at * {
    status: 'Feeling good',
    extraProperties: 'Yes!',
    [cause]: TypeError: Inner error
        at *
        at *
        at *
        at *
        at *
        at *
        at *
  }
}
RangeError: New Stack Frames
    at *
    at * {
  [cause]: Error: Stack causes
      at *
      at *
      ... * lines matching cause stack trace ...
      at * {
    [cause]: FoobarError: Individual message
        at *
        at *
        ... * lines matching cause stack trace ...
        at * {
      status: 'Feeling good',
      extraProperties: 'Yes!',
      [cause]: TypeError: Inner error
          at *
          at *
          at *
          at *
          at *
          at *
          at *
    }
  }
}
